// <auto-generated>
//     This code was generated by the .NET ToolStrip Customizer.
//     http://toolstripcustomizer.codeplex.com/
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Drawing;
using System.Text;
using System.Windows.Forms;

namespace WastedgeQuerier.Util
{
    public class VS2012ColorTable : ProfessionalColorTable
    {
        public override Color ButtonCheckedGradientBegin => Color.FromArgb(255, 254, 254, 254);
        public override Color ButtonCheckedGradientEnd => Color.FromArgb(255, 254, 254, 254);
        public override Color ButtonCheckedGradientMiddle => Color.FromArgb(255, 254, 254, 254);
        public override Color ButtonCheckedHighlight => ButtonCheckedGradientMiddle;
        public override Color ButtonCheckedHighlightBorder => ButtonSelectedBorder;
        public override Color ButtonPressedBorder => ButtonSelectedBorder;
        public override Color ButtonPressedGradientBegin => Color.FromArgb(255, 32, 172, 232);
        public override Color ButtonPressedGradientEnd => Color.FromArgb(255, 32, 172, 232);
        public override Color ButtonPressedGradientMiddle => Color.FromArgb(255, 32, 172, 232);
        public override Color ButtonPressedHighlight => ButtonPressedGradientMiddle;
        public override Color ButtonPressedHighlightBorder => ButtonPressedBorder;
        public override Color ButtonSelectedBorder => Color.FromArgb(255, 239, 239, 242);
        public override Color ButtonSelectedGradientBegin => Color.FromArgb(255, 254, 254, 254);
        public override Color ButtonSelectedGradientEnd => Color.FromArgb(255, 254, 254, 254);
        public override Color ButtonSelectedGradientMiddle => Color.FromArgb(255, 254, 254, 254);
        public override Color ButtonSelectedHighlight => ButtonSelectedGradientMiddle;
        public override Color ButtonSelectedHighlightBorder => ButtonSelectedBorder;
        public override Color CheckBackground => Color.FromArgb(255, 254, 254, 254);
        public override Color CheckPressedBackground => Color.FromArgb(255, 32, 172, 232);
        public override Color CheckSelectedBackground => Color.FromArgb(255, 254, 254, 254);
        public override Color GripDark => Color.FromArgb(255, 221, 226, 236);
        public override Color GripLight => Color.FromArgb(255, 204, 204, 219);
        public override Color ImageMarginGradientBegin => Color.FromArgb(255, 231, 232, 236);
        public override Color ImageMarginGradientEnd => Color.FromArgb(255, 231, 232, 236);
        public override Color ImageMarginGradientMiddle => Color.FromArgb(255, 231, 232, 236);
        public override Color ImageMarginRevealedGradientBegin => Color.FromArgb(255, 231, 232, 236);
        public override Color ImageMarginRevealedGradientEnd => Color.FromArgb(255, 231, 232, 236);
        public override Color ImageMarginRevealedGradientMiddle => Color.FromArgb(255, 231, 232, 236);
        public override Color MenuBorder => Color.FromArgb(255, 204, 206, 219);
        public override Color MenuItemBorder => Color.FromArgb(255, 231, 232, 236);
        public override Color MenuItemPressedGradientBegin => Color.FromArgb(255, 231, 232, 236);
        public override Color MenuItemPressedGradientEnd => Color.FromArgb(255, 231, 232, 236);
        public override Color MenuItemPressedGradientMiddle => Color.FromArgb(255, 231, 232, 236);
        public override Color MenuItemSelected => Color.FromArgb(255, 248, 249, 250);
        public override Color MenuItemSelectedGradientBegin => Color.FromArgb(255, 254, 254, 254);
        public override Color MenuItemSelectedGradientEnd => Color.FromArgb(255, 254, 254, 254);
        public override Color MenuStripGradientBegin => Color.FromArgb(255, 239, 239, 242);
        public override Color MenuStripGradientEnd => Color.FromArgb(255, 239, 239, 242);
        public override Color OverflowButtonGradientBegin => Color.FromArgb(255, 239, 239, 242);
        public override Color OverflowButtonGradientEnd => Color.FromArgb(255, 239, 239, 242);
        public override Color OverflowButtonGradientMiddle => Color.FromArgb(255, 239, 239, 242);
        public override Color RaftingContainerGradientBegin => Color.FromArgb(255, 186, 192, 201);
        public override Color RaftingContainerGradientEnd => Color.FromArgb(255, 186, 192, 201);
        public override Color SeparatorDark => Color.FromArgb(255, 204, 206, 219);
        public override Color SeparatorLight => Color.FromArgb(255, 246, 246, 246);
        public override Color StatusStripGradientBegin => Color.FromArgb(255, 79, 146, 219);
        public override Color StatusStripGradientEnd => Color.FromArgb(255, 79, 146, 219);
        public override Color ToolStripBorder => Color.FromArgb(0, 0, 0, 0);
        public override Color ToolStripContentPanelGradientBegin => Color.FromArgb(255, 239, 239, 242);
        public override Color ToolStripContentPanelGradientEnd => Color.FromArgb(255, 239, 239, 242);
        public override Color ToolStripDropDownBackground => Color.FromArgb(255, 231, 232, 236);
        public override Color ToolStripGradientBegin => Color.FromArgb(255, 239, 239, 242);
        public override Color ToolStripGradientEnd => Color.FromArgb(255, 239, 239, 242);
        public override Color ToolStripGradientMiddle => Color.FromArgb(255, 239, 239, 242);
        public override Color ToolStripPanelGradientBegin => Color.FromArgb(255, 239, 239, 242);
        public override Color ToolStripPanelGradientEnd => Color.FromArgb(255, 239, 239, 242);
    }
}